version: "3.9"

services:
  backend:
    build: ./backend
    container_name: faq_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/database.db:/app/database.db  # Persist SQLite database
      
    restart: always

  frontend:
    build: ./frontend
    container_name: faq_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always